<?php return '\'are_you_coming\' => \'required|boolean\',
\'number_of_items\' => \'required|numeric\',
\'start_date\' => \'required|date\',
\'end_date\' => \'required|date\',
\'tagged_at\' => \'required|date\',
\'first_name\' => \'required\',
\'last_name\' => \'required\',
\'address\' => \'required\',
\'city\' => \'nullable\',
\'no_type_here\' => \'nullable\',
\'state\' => \'required\',
\'zip_code\' => \'nullable\',
\'description\' => \'nullable\',
\'phone\' => \'nullable\',
\'user_test_id\' => \'nullable|numeric\',
\'email\' => \'nullable|email\',
\'company_url\' => \'nullable|url\',
';
